### ISSUE TITLE
Adapter assignment changed

### ISSUE THREAD

**Issue by mrova** [angular-ui/ui-scroll#110]
After update to version 1.5.1 all adapter assignments are no longer working for me.
```
<div ui-scroll-viewport="ui-scroll-viewport" class="coach_notes-msgs aacomment-wrap">
  <div class="coach_notes-msgs-inner">
    <div ui-scroll="item in MyDatasource" padding="0.5" buffer-size="25" start-index="1" adapter="vm.adapter" class="conversation_msg"></div>
  </div>
</div>
```

So in controller I was accessing it through `this.adapter` since controller was assigned to vm variable.
Now it's available through `$scope.$parent.vm.adapter`.

Is that expected behavior? 

Is this commit causing it?
https://github.com/angular-ui/ui-scroll/commit/8c714d507695d5479a6b7f0a082337ececea2385#diff-acd620d807e19ec97ee631f9cb480854

**Comment by mfeingold** [comment]
the original intention for the adapter access was to look it up starting from the scope associated with the viewport - this is how all other attributes work. As I was working on implementation of the `adapter on controller` syntax I discovered that for adapter only the lookup point is the scope associated with the scroller itself. So yes, I considered it to be a bug and fixed it to implement the expected behavior. I think in your situation it would be best to use the `adapter on controller` syntax
