### ISSUE TITLE
Not working in Internet Explorer. Missing Method array.find()

### ISSUE THREAD

**Issue by ChristianRosenau** [angular-ui/ui-scroll#112]
IE does not support that function prior to Edge

**Comment by dhilt** [comment]
I did a little research on current code browsers compatibility and found
out that this is the only thing that breaks IE9-11. So instead of injecting
a polyfill I decided to rewrite this piece of code. And the fix is already
in 'master' and it will be included in v1.5.2 release. Thanks a lot!

On Fri, Jul 8, 2016 at 12:46 PM, ChristianRosenau <notifications@github.com>
wrote:

> IE does not support that function prior to Edge
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular-ui/ui-scroll/issues/112>, or mute the thread
> <https://github.com/notifications/unsubscribe/AEKdXO_lRAf3hRwIlpNXwnbD51VMqQcSks5qThx3gaJpZM4JH4Tl>
> .
>



-- 
Алексанов Д.И.

**Comment by tobid** [comment]
Do you have a schedule for the v1.5.2 release? I would like to update ui-scroll in an application (from v1.3.2, webjar), but need IE compatibility.

**Comment by dhilt** [comment]
@tobid https://github.com/angular-ui/ui-scroll/issues/119 issue restrains us from 1.5.2. release, hope we'll fix it soon...

**Comment by dhilt** [comment]
@ChristianRosenau @tobid v1.5.2 is released, it includes the fix for this issue.
