### ISSUE TITLE
adapter not initialized inside a nf-if

### ISSUE THREAD

**Issue by jamartinezc** [angular-ui/ui-scroll#156]
Hi, the adapter is not initialized when the ui-scroll element is inside another element with ng-if. here is an [example](https://jsfiddle.net/vn25xvy9/) if you eliminate the ng-if, the adapter works just fine.

**Comment by dhilt** [comment]
@jamartinezc This is how Angular $parse works. Due to ui-scroll documentation "Angular $parse service is being used in assignable expressions implementation" and "the scroller will traverse its parents (from the ui-scroll element's scope up to the $rootScope) to locate the target scope". Ng-if creates a separate scope before your controller scope. And it stops $parse traversing. To avoid such situations Controller As syntax was introduced in Angular 1.2.

Here is exactly your case with intermediate ng-if: https://rawgit.com/angular-ui/ui-scroll/master/demo/controllerAs/controllerAs.html
