### ISSUE TITLE
When scroll the page very quickly,the page will be white for 1or 2 seconds

### ISSUE THREAD

**Issue by xiaozhaowen** [angular-ui/ui-scroll#175]

**Comment by dhilt** [comment]
@xiaozhaowen Since the ui-scroll has no mechanism to skip intermediate rows during fast scrollnig, the issue certainly depends on a) data retrieveing delay (remote overhead costs) and b) retrieved data rendering delay. First thing could be improved via cache (see [example](https://rawgit.com/angular-ui/ui-scroll/master/demo/cache/cache.html)). 

Also there are many useful words on this topic: https://github.com/angular-ui/ui-scroll/issues/120.
