### ISSUE TITLE
Webkit Overflow Scrolling & UI-Scroll

### ISSUE THREAD

**Issue by hohl** [angular-ui/ui-scroll#23]
UI-Scroll seems not be able to handle "smooth scrolling" on iOS and OS X devices correctly. To reproduce use an iOS device or a OS X device controlled by the trackpad and apply `-webkit-overflow-scrolling: touch` to the parent div of ui-scroll.

The scroller will load new content dynamically, but then once scrolling stops the scroller jumps to an incorrect position which can be quite confusing for the user (especially on small screens where you may not notice that you just jumped ~5 lines).

**Comment by mfeingold** [comment]
@dhilt can yo have a look?

**Comment by dhilt** [comment]
@mfeingold, Igor (@igorlimansky) confirmed that there is an issue, he also said that the presence of ui-scroll-viewport is mandatory...

**Comment by igorlimansky** [comment]
I've tested this issue in different ways, and only in one case it was possible to reproduce, with help of iPad and this fiddle(using customviewport example): http://jsfiddle.net/igorlimansky/qozrLLp8/6/
Should notice, that I couldn't catch '~5-6 lines jumps of scroller', but may be a few pixels occasionally, not so catchy to break user experience.
But on iPhone it seems smooth and working well.

Also, this property shouldn't work on OS X and it didn't ( goo.gl/g7WuOd -> mobile safari 5.0+ ).

It would be nice, if you could provide more details of how to reproduce this bug properly.

**Comment by hohl** [comment]
> Also, this property shouldn't work on OS X and it didn't ( goo.gl/g7WuOd -> mobile safari 5.0+ ).

`-webkit-overflow-scrolling` works the same way as it does on iOS when you use a touchpad for scrolling on your Mac.

**Comment by mfeingold** [comment]
Yea, it looks like we need your help in reproducing the issue. We tried multiple scenarios - Chrome vs Safari, iOS on iPad and iPhone, Mac OS, etc. In only a few of them we saw the effect similar to what you describe, but even then it is barely noticeable - it is jumping by a couple of pixels no more.

In general [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling) has the following disclaimer about this attribute `This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.`

Having said that is the impact you are describing the intended result of the attribute set to touch instead of auto? Just saying...

**Comment by OliverKK** [comment]
I ran into the same issue!
ui-scroll adds the style `overflow-y: auto` automatically to the container with the directive `ui-scroll-viewport` on it.
Is it possible to style this container by my self, without having automatically added styles by ui-scroll?

**Comment by mfeingold** [comment]
`overflow-y` on the viewport is necessary for the scroller to function properly. If you need to style the viewport in any other way - just go and do it
