### ISSUE TITLE
Adapter undefined

### ISSUE THREAD

**Issue by Thymo** [angular-ui/ui-scroll#67]
I'm receiving the following error: TypeError: Cannot read property 'reload' of undefined, when I call `$scope.adapter.reload(); ` 
ui-scroll is used inside a tbody:
`<tbody ui-scroll="transaction in bt.datasource"  adapter = "adapter" buffer-size="10" padding="0.3">`

**Comment by dhilt** [comment]
1st do you use "controller as" syntax? I guess the problem may be in `adapter = "bt.adapter"` or something like this; e.g. you defined adapter on some scope but call adapter.reload on another one
2nd you need to be careful with first reload call: you should not try to execute $scope.adapter.reload() before scroller is initialized because of reload()-method appears on adapter during linking process

**Comment by Thymo** [comment]
Thanks for the reply!
1. Yes, I'm using the "controller as" syntax, but I also tried without it by just using $scope and I'm receiving the same error. The $scope.adapter or vm.adapter remains undefined.
2. I'm trying to call call reload when the search query / filter changes.
3. I use angular 1.4.8 and ui-scroll 1.3.0

**Comment by dhilt** [comment]
Ok, I believe your issue is very simple, but you should provide us with a demo (something like https://jsfiddle.net/dhilt/ypdbmrt8/) and then we'll shortly help you! And also it would not be useless to take ui.scroll of higher version.

**Comment by Thymo** [comment]
When I copied the library from your jsfiddle in to a seperate directive file in my application it suddenly worked. I probably did something wrong with grunt or bower. Thanks for the help!

**Comment by dhilt** [comment]
Note that there is ui.scroll v1.3.2 in my jsfiddle. Btw if you will have any question on it please ask it!
