### ISSUE TITLE
problem loading ui.scroll.jqlite

### ISSUE THREAD

**Issue by lavagu** [angular-ui/ui-scroll#72]
I installed the ui-scroll with the ui-utils.

Even with the simple provided examples i'm getting error : viewport.offset is not function.

I tried to install the ui-scroll directly and now getting the error element.before is not a function
I know the issue is related to the jqlite, but can't add it in my bower. (errors). Where to to load it?

any help would be appreciated.

**Comment by mfeingold** [comment]
Did you include the ui-scroll-jqlite ([look here](https://github.com/angular-ui/ui-scroll#dependencies))

**Comment by lavagu** [comment]
if i add ui-scroll-jqlite as depency,, my app won't load due failed load of ui.scroll.jqlite module.

**Comment by lavagu** [comment]
some  more information.
i'm developping with gulp as buildsystem.

the vendor.js file in the .tmp is not containing the module ui.scroll.jqlite, only the ui.scroll. 
i'm new to angular, so where can i load the ui.scroll.jqlite module?

**Comment by lavagu** [comment]
solved my problem in a non elegant way (in my opinion)
i copied the content of ui.scroll.jqlite file into ui.scroll.
Now all is working fine. module is available.

**Comment by mackelito** [comment]
I´m actually having the same issue and for me copying the code into ui.scroll is not an option.. what am I missing?
The app loads when I don´t try to load 'ui.scroll.jqlite' ?

**Comment by mfeingold** [comment]
Can you post a repro?

**Comment by mackelito** [comment]
Just installed with npm and used webpack to create my build.js.

**Comment by dhilt** [comment]
@mackelito it would be nice if you could create a git-repository (or give me a link if it exists) which contains your problem. For I may clone it and fix the issue.

**Comment by chillyistkult** [comment]
The problem is that the package only includes `"main": "./dist/ui-scroll.js",` as the main file and not jqlite and therefore many automated build systems only inject this dependency (in index.html).

**Comment by dhilt** [comment]
@chillyistkult You know, "main" property could contain only one module link. And the problem is that ui-scroll has a _conditional_ dependency: jQuery or ui-scroll-jqlite. What solution could be suggested here (except manual builder settings managing)? I really would not wish to include ui-scroll-jqlite source code into ui-scroll.js...

**Comment by mackelito** [comment]
how about providing it as a separate module?

**Comment by chillyistkult** [comment]
@dhilt You are right, there can be only one main file, but normally the library should work without having to care about additional dependencies (that are not automatically resolved).

@mackelito Of course you could just add the missing dependency manually or (and that would be the best solution) add ui.scroll.jqlite as an independent module to bower and add the dependency to the bower.json of ui.scroll. That way automated build tools will be able to inject all the files that are needed to run ui-scroll. 

But it's still awkward to have ui.scroll.jqlite as an angular module instead of (like the jquery way) a global function.

**Comment by mackelito** [comment]
@dhilt just a small question.. what differs the ui-scroll.jqlite from the jqlite in angular?

**Comment by chillyistkult** [comment]
ui.scroll.jqlite adds a few methods like element.before and element.after (and others) that are originally not included in angular's jqlite. I guess the reason for @dhilt to maintain an own module just to add this needed methods was to keep the library as lightweight as possible without having a hard dependency on full jquery.

**Comment by dhilt** [comment]
A new version is released. Now jqLiteExtras service is a part of ui.scroll module. No need to apply it manually. The necessary check (for jQuery presence) and applying occure automatically during ui.scroll module run.

**Comment by dannydechtiar** [comment]
hi there, issue still exists. webpack returns "Can't resolve 'angular-ui-scroll'"
i do see the empty stub (sqlite file). 
v1.6.0

thanks ahead.

**Comment by dhilt** [comment]
The ui.scroll module has no more any dependencies since v1.6.0. The only
thing you need in your app is the "ui.scroll" module dependency. Are you
sure that you have cleaned all ui.scroll.jqlite mentions from your source
code? Or maybe you could  share your webpack config with us?
10 Фев 2017 г. 23:22 пользователь "dannydechtiar" <notifications@github.com>
написал:
