### ISSUE TITLE
Slow Painting/Rendering on Scroll

### ISSUE THREAD

**Issue by shawns582** [angular-ui/ui-scroll#80]
First off this is awesome, it gets rid of all the poor performance issues I was having with ng-repeat and provides improved scrolling over collection-repeat in ionic framework on android.

The issue I am having is that when I scroll, it initially reveals a white segement(background) and then paints over it from top to bottom.  This all happens in the viewport so it doesnt look good.  Im not sure what Im doing wrong or how I can fix it, Im fine with this painting happening outside of the viewport, just dont want it happening inside.  Thanks!

**Comment by mfeingold** [comment]
The white space you see there is padding element inserted by the scroller. Moving the scrollbar so that it becomes visible is what triggers the additional requests to pull more data. If the requests come back quickly the end user wont even see it, if not....

As elements scroll out of view and become invisible they are removed from buffer to save resources, but some of them stay. How many elements stay in the buffer even if they are not visible is controlled by the [`padding` attribute](https://github.com/angular-ui/ui-scroll#parameters) You can play with it to see if it will improve user experience.

I am not sure what else can be done to address your issue. Prevent user from scrolling to far beyond the padding?
